// protoc-gen-grpc-errors-go is a protoc plugin that generates type-safe
// error constants and registry initialization code from proto error definitions.
//
// Usage:
//
//	protoc --grpc-errors_out=. --grpc-errors_opt=paths=source_relative proto/*.proto
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

var version = "1.0.0"

func main() {
	showVersion := flag.Bool("version", false, "print version")
	flag.Parse()

	if *showVersion {
		fmt.Fprintf(os.Stderr, "protoc-gen-grpc-errors-go %s\n", version)
		os.Exit(0)
	}

	opts := protogen.Options{
		ParamFunc: func(name, value string) error {
			switch name {
			case "paths":
				// handled by protogen internally
			default:
				return fmt.Errorf("unknown parameter %q", name)
			}
			return nil
		},
	}

	opts.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

type errorDef struct {
	ErrorCode    string
	Message      string
	StatusCode   int
	Retryable    bool
	RetryDelayMs int64
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	var errors []errorDef

	// Parse file-level error definitions (field number 50002)
	fileOpts := file.Desc.Options()
	if fileOpts != nil {
		raw := fileOpts.(*descriptorpb.FileOptions)
		if raw != nil {
			if b, err := proto.Marshal(raw); err == nil {
				defs := parseExtensionErrors(b, 50002)
				errors = append(errors, defs...)
			}
		}
	}

	// Parse method-level error definitions (field number 50001)
	for _, svc := range file.Services {
		for _, method := range svc.Methods {
			opts := method.Desc.Options()
			if opts == nil {
				continue
			}

			raw := opts.(*descriptorpb.MethodOptions)
			if raw == nil {
				continue
			}

			b, err := proto.Marshal(raw)
			if err != nil {
				continue
			}

			defs := parseExtensionErrors(b, 50001)
			errors = append(errors, defs...)
		}
	}

	if len(errors) == 0 {
		return
	}

	// Deduplicate errors by code (same error may appear on multiple methods)
	seen := make(map[string]bool, len(errors))
	unique := make([]errorDef, 0, len(errors))
	for _, e := range errors {
		if e.ErrorCode == "" || !isValidErrorCode(e.ErrorCode) {
			continue
		}
		if !seen[e.ErrorCode] {
			seen[e.ErrorCode] = true
			unique = append(unique, e)
		}
	}
	errors = unique

	// Check if any error has a retry delay to decide on time import
	hasRetryDelay := false
	for _, e := range errors {
		if e.RetryDelayMs > 0 {
			hasRetryDelay = true
			break
		}
	}

	filename := file.GeneratedFilenamePrefix + "_grpc_errors.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-grpc-errors-go. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"errors"`)
	g.P()
	g.P(`	gerr "github.com/balcieren/grpc-errors-go"`)
	g.P()
	g.P(`	"google.golang.org/genproto/googleapis/rpc/errdetails"`)
	g.P(`	"google.golang.org/grpc/codes"`)
	if hasRetryDelay {
		g.P()
		g.P(`	"time"`)
	}
	g.P(")")
	g.P()

	// Generate error code constants (type-safe)
	g.P("// Error code constants for use with gerr.New, gerr.Wrap, etc.")
	g.P("const (")
	for _, e := range errors {
		varName := "Err" + errorCodeToConstant(e.ErrorCode)
		g.P(fmt.Sprintf("\t%s gerr.ErrorCode = %q", varName, e.ErrorCode))
	}
	g.P(")")
	g.P()

	// Generate init function
	g.P("func init() {")
	g.P("\tgerr.RegisterAll([]gerr.Error{")
	for _, e := range errors {
		constName := "Err" + errorCodeToConstant(e.ErrorCode)
		g.P("\t\t{")
		g.P(fmt.Sprintf("\t\t\tErrorCode:   %s,", constName))
		g.P(fmt.Sprintf("\t\t\tMessageTpl:  %q,", e.Message))
		g.P(fmt.Sprintf("\t\t\tStatusCode:  %s,", mapGrpcCode(e.StatusCode)))
		g.P(fmt.Sprintf("\t\t\tRetryable:   %t,", e.Retryable))
		if e.RetryDelayMs > 0 {
			g.P(fmt.Sprintf("\t\t\tRetryDelay:  %d * time.Millisecond,", e.RetryDelayMs))
		}
		g.P("\t\t},")
	}
	g.P("\t})")
	g.P("}")
	g.P()

	// Generate typed constructor functions with struct parameters
	g.P("// Typed constructor functions for compile-time safe error creation.")
	g.P("// Parameters are derived from {{placeholder}} fields in message templates.")
	for _, e := range errors {
		constName := "Err" + errorCodeToConstant(e.ErrorCode)
		baseName := errorCodeToConstant(e.ErrorCode)
		funcName := "NewErr" + baseName
		fields := extractTemplateFields(e.Message)

		if len(fields) == 0 {
			// No placeholders → no-arg constructor
			g.P(fmt.Sprintf("// %s creates an error for %s.", funcName, e.ErrorCode))
			g.P(fmt.Sprintf("func %s() error {", funcName))
			g.P(fmt.Sprintf("\treturn gerr.New(%s, nil)", constName))
			g.P("}")
		} else {
			// Generate params struct
			structName := baseName + "Params"
			g.P(fmt.Sprintf("// %s holds the template fields for %s.", structName, e.ErrorCode))
			g.P(fmt.Sprintf("type %s struct {", structName))
			for _, f := range fields {
				g.P(fmt.Sprintf("\t%s string", fieldToExportedName(f)))
			}
			g.P("}")
			g.P()

			// Generate constructor
			g.P(fmt.Sprintf("// %s creates an error for %s.", funcName, e.ErrorCode))
			g.P(fmt.Sprintf("func %s(p %s) error {", funcName, structName))

			// Build gerr.M{} from struct fields
			var mapEntries []string
			for _, f := range fields {
				mapEntries = append(mapEntries, fmt.Sprintf("%q: p.%s", f, fieldToExportedName(f)))
			}
			g.P(fmt.Sprintf("\treturn gerr.New(%s, gerr.M{%s})", constName, strings.Join(mapEntries, ", ")))
			g.P("}")
		}
		g.P()
	}

	// Generate client-side IsXxx error matchers
	g.P("// Client-side error matchers for checking errors returned by gRPC calls.")
	g.P("// They check the google.rpc.ErrorInfo detail as well as the x-error-code trailer.")
	for _, e := range errors {
		baseName := errorCodeToConstant(e.ErrorCode)
		constName := "Err" + baseName
		funcName := "Is" + baseName
		g.P(fmt.Sprintf("// %s reports whether err is a %s error.", funcName, e.ErrorCode))
		g.P(fmt.Sprintf("func %s(err error) bool {", funcName))
		g.P("\t// Check via google.rpc.ErrorInfo (fast path)")
		g.P(fmt.Sprintf("\treturn gerr.MatchesError(err, %s)", constName))
		g.P("}")
		g.P()
	}

	// Generate typed ErrorInfo extractors
	g.P("// Typed ErrorInfo extractors for pulling structured metadata from errors.")
	for _, e := range errors {
		baseName := errorCodeToConstant(e.ErrorCode)
		isFuncName := "Is" + baseName
		extractFuncName := "Extract" + baseName + "Info"
		g.P(fmt.Sprintf("// %s extracts the google.rpc.ErrorInfo from a %s error, if matching.", extractFuncName, e.ErrorCode))
		g.P(fmt.Sprintf("func %s(err error) *errdetails.ErrorInfo {", extractFuncName))
		g.P(fmt.Sprintf("\tif !%s(err) {", isFuncName))
		g.P("\t\treturn nil")
		g.P("\t}")
		g.P("\tinfo, ok := gerr.ExtractErrorInfo(err)")
		g.P("\tif !ok {")
		g.P("\t\treturn nil")
		g.P("\t}")
		g.P("\treturn info")
		g.P("}")
		g.P()
	}
}

// parseExtensionErrors extracts ErrorDef messages from wire-format options
// by looking for the specified field number.
func parseExtensionErrors(b []byte, fieldNum protowire.Number) []errorDef {
	var defs []errorDef
	for len(b) > 0 {
		num, wtype, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]

		switch wtype {
		case protowire.VarintType:
			_, n = protowire.ConsumeVarint(b)
		case protowire.Fixed32Type:
			_, n = protowire.ConsumeFixed32(b)
		case protowire.Fixed64Type:
			_, n = protowire.ConsumeFixed64(b)
		case protowire.BytesType:
			v, vn := protowire.ConsumeBytes(b)
			n = vn
			if num == fieldNum && n > 0 {
				if def, ok := parseErrorDef(v); ok {
					defs = append(defs, def)
				}
			}
		case protowire.StartGroupType:
			_, n = protowire.ConsumeGroup(num, b)
		default:
			return defs
		}

		if n < 0 {
			break
		}
		b = b[n:]
	}
	return defs
}

// parseErrorDef parses a single ErrorDef message from wire-format bytes.
// ErrorDef fields: error_code(1), message(2), status_code(3), retryable(4), retry_delay_ms(5).
func parseErrorDef(b []byte) (errorDef, bool) {
	var def errorDef
	var found bool
	for len(b) > 0 {
		num, wtype, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]

		switch wtype {
		case protowire.BytesType:
			v, vn := protowire.ConsumeBytes(b)
			n = vn
			switch num {
			case 1:
				def.ErrorCode = string(v)
				found = true
			case 2:
				def.Message = string(v)
				found = true
			}
		case protowire.VarintType:
			v, vn := protowire.ConsumeVarint(b)
			n = vn
			switch num {
			case 3:
				def.StatusCode = int(v)
				found = true
			case 4:
				def.Retryable = v != 0
				found = true
			case 5:
				def.RetryDelayMs = int64(v)
				found = true
			}
		default:
			// Skip unknown wire types
			switch wtype {
			case protowire.Fixed32Type:
				_, n = protowire.ConsumeFixed32(b)
			case protowire.Fixed64Type:
				_, n = protowire.ConsumeFixed64(b)
			case protowire.StartGroupType:
				_, n = protowire.ConsumeGroup(num, b)
			default:
				return def, false
			}
		}

		if n < 0 {
			break
		}
		b = b[n:]
	}
	return def, found
}

func errorCodeToConstant(code string) string {
	name := strings.TrimPrefix(code, "ERROR_")
	parts := strings.Split(name, "_")
	var result string
	for _, p := range parts {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
		}
	}
	return result
}

// isValidErrorCode reports whether the error code contains only characters
// that produce valid Go identifiers ([A-Za-z0-9_] with at least one letter).
func isValidErrorCode(code string) bool {
	if code == "" {
		return false
	}
	hasLetter := false
	for _, r := range code {
		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') {
			hasLetter = true
			continue
		}
		if r >= '0' && r <= '9' {
			continue
		}
		if r == '_' {
			continue
		}
		return false
	}
	return hasLetter
}

// extractTemplateFields parses {{placeholder}} names from a message template.
// Returns unique fields in order of first appearance. Invalid field names
// (containing characters other than [a-zA-Z0-9_]) are silently skipped.
func extractTemplateFields(message string) []string {
	var fields []string
	seen := make(map[string]bool)
	i := 0
	for i < len(message) {
		start := strings.Index(message[i:], "{{")
		if start == -1 {
			break
		}
		start += i
		end := strings.Index(message[start:], "}}")
		if end == -1 {
			break
		}
		end += start
		field := message[start+2 : end]
		if field != "" && !seen[field] && isValidFieldName(field) {
			seen[field] = true
			fields = append(fields, field)
		}
		i = end + 2
	}
	return fields
}

// isValidFieldName reports whether the template field name contains only
// characters that produce valid Go struct field names ([a-zA-Z0-9_]).
func isValidFieldName(field string) bool {
	if field == "" {
		return false
	}
	for _, r := range field {
		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') {
			continue
		}
		if r >= '0' && r <= '9' {
			continue
		}
		if r == '_' {
			continue
		}
		return false
	}
	return true
}

// fieldToExportedName converts a snake_case template field to a PascalCase Go exported name.
// e.g. "product_id" → "ProductId", "email" → "Email"
func fieldToExportedName(field string) string {
	parts := strings.Split(field, "_")
	var result string
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		result += strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
	}
	return result
}

// grpcCodeMap maps google.rpc.Code numeric values to gRPC code constants.
var grpcCodeMap = map[int]string{
	1:  "codes.Canceled",
	2:  "codes.Unknown",
	3:  "codes.InvalidArgument",
	4:  "codes.DeadlineExceeded",
	5:  "codes.NotFound",
	6:  "codes.AlreadyExists",
	7:  "codes.PermissionDenied",
	8:  "codes.ResourceExhausted",
	9:  "codes.FailedPrecondition",
	10: "codes.Aborted",
	11: "codes.OutOfRange",
	12: "codes.Unimplemented",
	13: "codes.Internal",
	14: "codes.Unavailable",
	15: "codes.DataLoss",
	16: "codes.Unauthenticated",
}

func mapGrpcCode(code int) string {
	if v, ok := grpcCodeMap[code]; ok {
		return v
	}
	return "codes.Internal"
}